"""update user

Revision ID: bae352826db8
Revises: fcc7ceb8f51e
Create Date: 2023-01-11 09:16:42.176051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae352826db8'
down_revision = 'fcc7ceb8f51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###
