"""empty message

Revision ID: fcc7ceb8f51e
Revises: 
Create Date: 2023-01-05 04:02:22.774024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc7ceb8f51e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('banners', sa.Column('subtitle', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'subtitle')
    op.drop_column('banners', 'title')
    # ### end Alembic commands ###
